services:
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.11.0
    ports:
     - "16686:16686"
     - "4317:4317"
  prometheus:
    image: prom/prometheus:v3.7.3
    ports:
     - "9090:9090"
    volumes:
     -  ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
     -  '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana:12.3.0-18925857539-ubuntu
    ports:
        - "3000:3000"
    volumes:
        -  ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  loki:
    image: grafana/loki:3.5
    ports:
        - "3100:3100"